name: test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  install-test-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    container: cypress/browsers:node18.6.0-chrome105-ff104
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - name: Cypress info
        run: npx cypress info
      - name: Set API key
        run: sh setup.sh ${{ secrets.ORS_API_KEY }}
      - name: Run tests
        run: npm run test:ci
      - name: Upload coverage
        uses: codecov/codecov-action@v3
